### PR TITLE
Use svg demo

### PR DESCRIPTION
**Pull request by marionebl**
* reduces file size from 400kb to 39kb
* sources at https://gist.github.com/marionebl/6ef5b206666e657cb6fd6840df652805#file-example-svg
* scriptabe via https://gist.github.com/marionebl/6ef5b206666e657cb6fd6840df652805#file-example-sh

### CODE REVIEW

**Comment by marionebl** [comment]
Any news? I'd like to close this if you are not interested to keep my open PR view useful.

**Comment by watson** [comment]
Wow, this is quite a lot of work you've put into this! Thank you 😃 

Where's the svg-term-cli tool you're using?

**Comment by marionebl** [comment]
Used it as a global install of `svg-term-cli`. Would you prefer having 

* example.js
* example.sh

as part of this repo? `svg-term-cli` could be pulled in as `devDependency` then.

**Comment by watson** [comment]
Could you make an `example` folder that contains the example and related assets?

Then to make it easy, you can add `svg-term-cli` as a dev dependency as you said and then also make an npm script to update the svg. E.g. `npm run example`.

Then also make an `.npmignore` to ignore the `example` folder so it's not published with the npm package. And while you're at it, just add `.travis.yml` and `test.js` to the ignore file also 😃

**Comment by marionebl** [comment]
Done!

* Add `example/` setup
* Add `svg-term-cli`, `ansi-diff-stream` as `devDependencies`
* Change to relative img src, possible after fixes by GitHub ❤️. See marionebl/svg-term-cli#5

**Edit**:

* ~~Specifiy explicit `files[]`~~
* Add `.npmignore`

**Comment by watson** [comment]
I prefer to use a blacklist via `.npmignore` file instead of a whitelist via the `files` property in `package.json`, as it's too easy to forget to add new files to the `files` property. And that will not be caught in tests unfortunately.

**Comment by marionebl** [comment]
> I prefer to use a blacklist via .npmignore file instead of a whitelist via the files property in package.json, as it's too easy to forget to add new files to the files property. And that will not be caught in tests unfortunately.

Ok, adapted accordingly

**Comment by watson** [comment]
Thank you so much for taking the time to do this 😃 I think I have a few other projects where I want to use that svg tool!

**Comment by marionebl** [comment]
Glad you like it :)

**Pull request merged**
